name: 'Build and publish Docker container'
on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build:
    runs-on: [ubuntu-latest]
    name: Build and publish Docker container
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: |
          docker context create builders
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          endpoint: builders
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push backend image
        uses: docker/build-push-action@v3.2.0
        with:
          context: backend
          file: backend/Dockerfile
          tags: bl19dev/sumhub-backend:main
          push: true
          platforms: linux/amd64
      - name: Build and push backend image
        uses: docker/build-push-action@v3.2.0
        with:
          context: frontend/sumhub
          file: frontend/sumhub/Dockerfile
          tags: bl19dev/sumhub-frontend:main
          push: true
          platforms: linux/amd64
